server:
  port: 8080  
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE  
          predicates:
            - Path=/api/customers/**  
        - id: account-service
          uri: lb://ACCOUNT-SERVICE  
          predicates:
            - Path=/api/accounts/**  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  
