server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yougame
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    user:
      password: password  # Only for testing; remove in production

jwt:
  header:
    string: Cookie
  signing:
    key: 76k9ldfs2jkLJF8561fdsSffs32WO3140933fs852oHi31hsjd13DFFvc31x843yth279fsikhgf31uOIUREkhfWery45333121298324KJHFEQ103fds12PAODNCZXIO8132ljfd
  authorities:
    key: roles
  token:
    validity: '3600000'  # 1 hour in milliseconds

# logging:
#   level:
#     org:
#       springframework:
#         security: DEBUG
#         web: DEBUG
